#pragma once

#include "RayGE/APIs/Scene.h"

RayGE_ResourceHandle SceneAPI_CreateEntity(void);
RayGE_Component_Spatial* SceneAPI_AddSpatialComponent(RayGE_ResourceHandle entity);
RayGE_Component_Spatial* SceneAPI_GetSpatialComponent(RayGE_ResourceHandle entity);
RayGE_Component_Camera* SceneAPI_AddCameraComponent(RayGE_ResourceHandle entity);
RayGE_Component_Camera* SceneAPI_GetCameraComponent(RayGE_ResourceHandle entity);
RayGE_Component_Renderable* SceneAPI_AddRenderableComponent(RayGE_ResourceHandle entity);
RayGE_Component_Renderable* SceneAPI_GetRenderableComponent(RayGE_ResourceHandle entity);
