name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build-linux:
    name: Build on Ubuntu
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y libsdl2-dev

    - name: Build
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{runner.workspace}}/build
        cc: gcc
        cxx: g++
        build-type: MinSizeRel
        target: all

  # The Zig compiler is pretty good at finding more subtle issues in code
  build-linux-zig-cc:
    name: Build on Ubuntu with Zig compiler
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt update && \
        sudo apt install -y libsdl2-dev libx11-dev && \
        sudo snap install zig --classic --beta

    - name: Build
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{runner.workspace}}/build
        build-type: MinSizeRel
        target: all
        configure-options: "-DCMAKE_TOOLCHAIN_FILE=${{runner.workspace}}/rayge/cmake/zig-cmake-toolchains/zig-toolchain-x86_64-linux-gnu.cmake"

  build-windows:
    name: Build on Windows
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: choco install ninja

    - name: Build
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{runner.workspace}}/build
        build-type: MinSizeRel
        target: all
        configure-options: -G Ninja
